import Footer from "@/components/footer";
import localFont from "next/font/local";
import "./globals.css";
import "/public/style.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="cs" className="scroll-smooth">
      <body className="normalniText-300 max-w-4xl mx-auto text-gray-800">
        {children}
      </body>
      <Footer />
    </html>
  );
}
