export const nabidka = [
  {
    id: 1,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=1",
  },
  {
    id: 2,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=2",
  },
  {
    id: 3,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=3",
  },
  {
    id: 4,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=4",
  },
  {
    id: 5,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=5",
  },
  {
    id: 6,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=6",
  },
  {
    id: 7,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=7",
  },
  {
    id: 8,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=8",
  },
  {
    id: 9,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=9",
  },
  {
    id: 10,
    title: "cheese",
    description: "cheese description",
    price: 100,
    image: "https://dummyimage.com/200x200.png?text=10",
  },
];
